# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.srcs/sources_1/new/Project_7u7d.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.xdc
set_property used_in_implementation false [get_files C:/Users/user/Desktop/COL215LAB/Project/Project_7u7d/Project_7u7d.xdc]


synth_design -top Project_7u7d -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Project_7u7d.dcp

catch { report_utilization -file Project_7u7d_utilization_synth.rpt -pb Project_7u7d_utilization_synth.pb }
